sudo: required
services:
  - docker

before_install:
  - docker build -t osjmeg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true osjmeg/react-test npm test

after_success:
  - docker build -t osjmeg/multi-client ./client
  - docker build -t osjmeg/multi-nginx ./nginx
  - docker build -t osjmeg/multi-server ./server
  - docker build -t osjmeg/multi-worker ./worker

  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push osjmeg/multi-client
  - docker push osjmeg/multi-nginx
  - docker push osjmeg/multi-server
  - docker push osjmeg/multi-worker

  